# Generated by Django 4.2.2 on 2023-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('big', 'big'), ('middle', 'middle'), ('minivan', 'minivan')],
                                          max_length=100, null=True)),
            ],
        ),
    ]
