# Generated by Django 4.2.2 on 2023-07-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(choices=[('big', 'big'), ('middle', 'middle'), ('minivan', 'minivan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='straxovka',
            field=models.FileField(upload_to=''),
        ),
    ]
