# Generated by Django 4.2.2 on 2023-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company_dot_number_alter_driver_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_driver',
            field=models.IntegerField(null=True),
        ),
    ]
